version: '3'

services:
  db:
    image: geographica/postgis:dev_diplodocus
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWD=password
    expose:
    - 5432
  app:
    build: .
    command: python service.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
